# Generated by Django 3.2.4 on 2021-06-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.FloatField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('category', models.ManyToManyField(blank=True, related_name='product', to='category_api.Category')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
